import { AnalysisReport } from '../types/index.js';
import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { createLogger } from '../utils/logger.js';

const logger = createLogger('markdown-exporter');

export class MarkdownExporter {
  async export(report: AnalysisReport, outputPath: string): Promise<void> {
    try {
      const fullPath = resolve(outputPath, 'git-spark-report.md');

      // Ensure directory exists
      mkdirSync(dirname(fullPath), { recursive: true });

      // Generate Markdown content
      const markdownContent = this.generateMarkdown(report);

      // Write to file
      writeFileSync(fullPath, markdownContent, 'utf-8');

      logger.info('Markdown report exported successfully', { path: fullPath });
    } catch (error) {
      logger.error('Failed to export Markdown report', {
        error:
          error instanceof Error
            ? {
                message: error.message,
                name: error.name,
                stack: error.stack,
              }
            : error,
        outputPath,
      });
      throw error;
    }
  }

  private generateMarkdown(report: AnalysisReport): string {
    const { repository, summary, authors, files, risks, governance } = report;

    return `# 🔥 Git Spark Report

Generated on ${report.metadata.generatedAt.toLocaleDateString()}

## 📊 Executive Summary

**Repository Health: ${summary.healthRating.toUpperCase()}**

| Metric | Value |
|--------|-------|
| Total Commits | ${repository.totalCommits} |
| Contributors | ${repository.totalAuthors} |
| Files Changed | ${repository.totalFiles} |
| Health Score | ${Math.round(repository.healthScore * 100)}% |
| Bus Factor | ${Math.round((repository.busFactor / repository.totalAuthors) * 100)}% |

${
  summary.insights.length > 0
    ? `
### 💡 Key Insights

${summary.insights.map(insight => `- ${insight}`).join('\n')}
`
    : ''
}

${
  summary.actionItems.length > 0
    ? `
### 🚨 Action Items

${summary.actionItems.map(item => `- ${item}`).join('\n')}
`
    : ''
}

## 📁 Repository Overview

- **Active Period:** ${repository.activeDays} days
- **Average Commits/Day:** ${repository.avgCommitsPerDay.toFixed(2)}
- **Total Code Churn:** ${repository.totalChurn.toLocaleString()} lines
- **Governance Score:** ${Math.round(governance.score * 100)}%

### 💻 Languages

${Object.entries(repository.languages)
  .map(([lang, count]) => `- ${lang}: ${count}`)
  .join('\n')}

## 👥 Top Contributors

| Author | Commits | Churn | Files | Avg Commit Size |
|--------|---------|-------|-------|-----------------|
${authors
  .slice(0, 10)
  .map(
    author =>
      `| ${author.name} | ${author.commits} | ${author.churn.toLocaleString()} | ${author.filesChanged} | ${Math.round(author.avgCommitSize)} |`
  )
  .join('\n')}

## 🔥 File Hotspots

| File | Commits | Authors | Churn | Risk Score |
|------|---------|---------|-------|------------|
${files
  .slice(0, 15)
  .map(
    file =>
      `| \`${file.path}\` | ${file.commits} | ${file.authors.length} | ${file.churn.toLocaleString()} | ${Math.round(file.riskScore * 100)}% |`
  )
  .join('\n')}

## ⚠️ Risk Analysis

**Overall Risk Level: ${risks.overallRisk.toUpperCase()}**

### Risk Factors
- High churn files: ${risks.riskFactors.highChurnFiles}
- Files with many authors: ${risks.riskFactors.manyAuthorFiles}
- Large commits: ${risks.riskFactors.largeCommits}
- Recently changed files: ${risks.riskFactors.recentChanges}

## 📋 Governance Analysis

**Governance Score: ${Math.round(governance.score * 100)}%**

- **Conventional Commits:** ${governance.conventionalCommits}
- **Traceability Score:** ${Math.round(governance.traceabilityScore * 100)}%
- **Average Message Length:** ${Math.round(governance.avgMessageLength)} characters
- **WIP Commits:** ${governance.wipCommits}
- **Revert Commits:** ${governance.revertCommits}
- **Short Messages:** ${governance.shortMessages}

${report.azureDevOps ? this.generateAzureDevOpsMarkdown(report.azureDevOps) : ''}

---

*Generated by git-spark v${report.metadata.version} in ${report.metadata.processingTime}ms*
`;
  }

  /**
   * Generate Azure DevOps integration section for Markdown
   */
  private generateAzureDevOpsMarkdown(azureDevOps: any): string {
    const { summary, pullRequests, reviewProcess, gitIntegration, teamCollaboration, dataQuality } =
      azureDevOps;

    const formatPercent = (value: number) => `${Math.round(value * 100)}%`;
    const formatNumber = (n: number) => new Intl.NumberFormat().format(n);

    return `
## 🔗 Azure DevOps Integration

Pull request analytics and team collaboration insights from Azure DevOps, correlated with Git commit data.

### 📊 Overview

| Metric | Value |
|--------|-------|
| Total Pull Requests | ${formatNumber(summary.totalPullRequests)} |
| Analysis Period | ${summary.dateRange.start.toLocaleDateString()} - ${summary.dateRange.end.toLocaleDateString()} |
| Git Commit Coverage | ${formatPercent(summary.coverage.gitCommitCoverage)} |
| Cache Hit Rate | ${formatPercent(summary.dataFreshness.cacheHitRate)} |

### 📋 Pull Request Metrics

#### Size Distribution
- **Small (<10 files):** ${pullRequests.sizeDistribution.small} PRs
- **Medium (10-50 files):** ${pullRequests.sizeDistribution.medium} PRs
- **Large (50-200 files):** ${pullRequests.sizeDistribution.large} PRs
- **X-Large (>200 files):** ${pullRequests.sizeDistribution.xlarge} PRs

#### Timing Metrics
- **Average Time to Merge:** ${pullRequests.timing.averageTimeToMerge.toFixed(1)} hours
- **Median Time to Merge:** ${pullRequests.timing.medianTimeToMerge.toFixed(1)} hours
- **90th Percentile:** ${pullRequests.timing.percentileMetrics.p90TimeToMerge.toFixed(1)} hours

#### Status Breakdown
- **Completed:** ${pullRequests.statusBreakdown.completed}
- **Active:** ${pullRequests.statusBreakdown.active}
- **Abandoned:** ${pullRequests.statusBreakdown.abandoned}

### 👥 Review Process

#### Participation
- **Average Reviewers per PR:** ${reviewProcess.participation.averageReviewersPerPR.toFixed(1)}
- **Self-Approval Rate:** ${formatPercent(reviewProcess.participation.selfApprovalRate)}

#### Quality Metrics
- **Approval Rate:** ${formatPercent(reviewProcess.quality.approvalRate)}
- **Rejection Rate:** ${formatPercent(reviewProcess.quality.rejectionRate)}
- **Thoroughness Score:** ${formatPercent(reviewProcess.quality.thoroughnessScore)}

### 🔗 Git Integration Analysis

- **Mapping Success Rate:** ${formatPercent(gitIntegration.mappingSuccessRate)}

#### Integration Methods
- **Merge Commits:** ${gitIntegration.integrationMethods.mergeCommit}
- **Squash Commits:** ${gitIntegration.integrationMethods.squashCommit}
- **Branch Analysis:** ${gitIntegration.integrationMethods.branchAnalysis}
- **Manual Links:** ${gitIntegration.integrationMethods.manualLink}

#### Integration Quality
- **High Confidence:** ${gitIntegration.integrationQuality.highConfidenceAssociations}
- **Medium Confidence:** ${gitIntegration.integrationQuality.mediumConfidenceAssociations}
- **Low Confidence:** ${gitIntegration.integrationQuality.lowConfidenceAssociations}
- **Unmapped:** ${gitIntegration.integrationQuality.unmappedCommits}

### 🤝 Team Collaboration

#### Top PR Creators
${teamCollaboration.creationPatterns.mostActivePRCreators
  .slice(0, 5)
  .map(
    (creator: { creator: string; prCount: number }) =>
      `- **${creator.creator}:** ${creator.prCount} PRs`
  )
  .join('\n')}

#### Team Health Metrics
- **Collaboration Score:** ${formatPercent(teamCollaboration.teamDynamics.collaborationScore)}
- **Cross-Review Rate:** ${formatPercent(teamCollaboration.crossTeamCollaboration.crossReviewRate)}
- **Knowledge Sharing Score:** ${formatPercent(teamCollaboration.crossTeamCollaboration.knowledgeSharingScore)}
- **Creation Distribution (Gini):** ${teamCollaboration.creationPatterns.creationDistribution.toFixed(3)}

### 📈 Data Quality Assessment

#### Completeness
- **PR Data Completeness:** ${formatPercent(dataQuality.completeness.prDataCompleteness)}
- **Review Data Completeness:** ${formatPercent(dataQuality.completeness.reviewDataCompleteness)}
- **Commit Association Rate:** ${formatPercent(dataQuality.completeness.commitAssociationRate)}

#### Confidence Levels
- **Timing Metrics:** ${dataQuality.confidence.timingMetrics}
- **Review Metrics:** ${dataQuality.confidence.reviewMetrics}
- **Collaboration Metrics:** ${dataQuality.confidence.collaborationMetrics}

#### Recommendations
${dataQuality.recommendations.map((rec: string) => `- ${rec}`).join('\n')}

### 🔍 Integration Notes

This analysis combines Azure DevOps pull request data with Git commit history to provide comprehensive insights into development workflows and team collaboration patterns.

**Data Sources:** Azure DevOps REST API (pull requests, reviewers) + Git repository (commits, file changes)

**Limitations:** Review timing data requires additional API calls not currently implemented. Team structure and organizational context not available from API data alone.
`;
  }
}
